// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("server.Models.Entities.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricFileDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricFileDefinitionId");

                    b.HasIndex("MetricId");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("server.Models.Entities.ImportRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("ImportRows");
                });

            modelBuilder.Entity("server.Models.Entities.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PremiumMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PremiumMethodId");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("server.Models.Entities.MetricFieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcelColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricFileDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemFieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationRule")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MetricFileDefinitionId");

                    b.ToTable("MetricFieldMappings");
                });

            modelBuilder.Entity("server.Models.Entities.MetricFileDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeaderRowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetricId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("MetricFileDefinitions");
                });

            modelBuilder.Entity("server.Models.Entities.PremiumMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalculationPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MethodNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PremiumPercentage")
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MethodNumber")
                        .IsUnique();

                    b.ToTable("PremiumMethods");
                });

            modelBuilder.Entity("server.Models.Entities.ImportBatch", b =>
                {
                    b.HasOne("server.Models.Entities.MetricFileDefinition", "MetricFileDefinition")
                        .WithMany()
                        .HasForeignKey("MetricFileDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Models.Entities.Metric", "Metric")
                        .WithMany("ImportBatches")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Metric");

                    b.Navigation("MetricFileDefinition");
                });

            modelBuilder.Entity("server.Models.Entities.ImportRow", b =>
                {
                    b.HasOne("server.Models.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("server.Models.Entities.Metric", b =>
                {
                    b.HasOne("server.Models.Entities.PremiumMethod", "PremiumMethod")
                        .WithMany("Metrics")
                        .HasForeignKey("PremiumMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PremiumMethod");
                });

            modelBuilder.Entity("server.Models.Entities.MetricFieldMapping", b =>
                {
                    b.HasOne("server.Models.Entities.MetricFileDefinition", "MetricFileDefinition")
                        .WithMany("FieldMappings")
                        .HasForeignKey("MetricFileDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetricFileDefinition");
                });

            modelBuilder.Entity("server.Models.Entities.MetricFileDefinition", b =>
                {
                    b.HasOne("server.Models.Entities.Metric", "Metric")
                        .WithMany("FileDefinitions")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("server.Models.Entities.ImportBatch", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("server.Models.Entities.Metric", b =>
                {
                    b.Navigation("FileDefinitions");

                    b.Navigation("ImportBatches");
                });

            modelBuilder.Entity("server.Models.Entities.MetricFileDefinition", b =>
                {
                    b.Navigation("FieldMappings");
                });

            modelBuilder.Entity("server.Models.Entities.PremiumMethod", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
